///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Images {
  Images._();

  static const String assetsImagesFavouriteIcon = 'assets/images/favourite_icon.svg';
  static const String fontsPoppinsRegular = 'assets/fonts/Poppins-Regular.ttf';
  static const String imagesAddIcon = 'assets/images/add_icon.svg';
  static const String imagesFavouriteIcon = 'assets/images/favourite_icon.svg';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesSearchIcon = 'assets/images/search_icon.svg';
  static const String imagesShoppingIcon = 'assets/images/shopping_icon.svg';
  static const String imagesStarIcon = 'assets/images/star_icon.svg';

}
